services:
  django:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  vue:
    build:
      context: .
      dockerfile: frontend/Dockerfile 
    ports:
      - "3000:3000"
    depends_on:
      - django
    env_file:
      - ./.env


